<?xml version="1.0" encoding="utf-8"?><Database Name="BetterTech_DB" Class="DataLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\BetterTech_DB.mdf;Integrated Security=True" SettingsObjectName="BetterTech_Webpage.Properties.Settings" SettingsPropertyName="BetterTech_DBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Item" Member="Items">
    <Type Name="Item">
      <Column Name="Invoice_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Product_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Item_Qty" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Item_SellingPrice" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Association Name="Product_Item" Member="Product" ThisKey="Product_Id" OtherKey="Product_Id" Type="Product" IsForeignKey="true" />
      <Association Name="Invoice_Item" Member="Invoice" ThisKey="Invoice_Id" OtherKey="Invoice_Id" Type="Invoice" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Wishlist" Member="Wishlists">
    <Type Name="Wishlist">
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Product_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="User_Wishlist" Member="User" ThisKey="Username" OtherKey="Username" Type="User" IsForeignKey="true" />
      <Association Name="Product_Wishlist" Member="Product" ThisKey="Product_Id" OtherKey="Product_Id" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(56) NOT NULL" CanBeNull="false" />
      <Column Name="UserType" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AddressLine1" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="AddressLine2" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="ZipCode" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DateRegistered" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="User_Wishlist" Member="Wishlists" ThisKey="Username" OtherKey="Username" Type="Wishlist" />
      <Association Name="User_Cart" Member="Carts" ThisKey="Username" OtherKey="Username" Type="Cart" />
      <Association Name="User_Invoice" Member="Invoices" ThisKey="Username" OtherKey="Username" Type="Invoice" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="Product_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Product_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Product_Price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Product_Description" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Product_Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Product_Img" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Product_NumSold" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Product_OnHand" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Product_IsSpecial" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Product_SpclPercantage" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="Product_Brand" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Product_DateAdded" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Product_IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Product_Item" Member="Items" ThisKey="Product_Id" OtherKey="Product_Id" Type="Item" />
      <Association Name="Product_Wishlist" Member="Wishlists" ThisKey="Product_Id" OtherKey="Product_Id" Type="Wishlist" />
      <Association Name="Product_Cart" Member="Carts" ThisKey="Product_Id" OtherKey="Product_Id" Type="Cart" />
    </Type>
  </Table>
  <Table Name="dbo.Cart" Member="Carts">
    <Type Name="Cart">
      <Column Name="Cart_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Product_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Product_Cart" Member="Product" ThisKey="Product_Id" OtherKey="Product_Id" Type="Product" IsForeignKey="true" />
      <Association Name="User_Cart" Member="User" ThisKey="Username" OtherKey="Username" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Invoice" Member="Invoices">
    <Type Name="Invoice">
      <Column Name="Invoice_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Invoice_Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Invoice_Total" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Association Name="Invoice_Item" Member="Items" ThisKey="Invoice_Id" OtherKey="Invoice_Id" Type="Item" />
      <Association Name="User_Invoice" Member="User" ThisKey="Username" OtherKey="Username" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
</Database>